name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - uses: rwe/actions-hlint-setup@v1
      - name: Lint and Build
        run: |
          ./Shakefile.hs
